SELECT
    TRANSACTION_STATUS_KEY,
    COUNT(*) AS ROW_CNT,
    COUNT(DISTINCT TRANSACTION_IDENTIFIER) AS DISTINCT_TXN_CNT,
    SUM(MEASURE_VOLUME) AS SUM_MEASURE_VOLUME
FROM BDP_UK_CARDS.FACT_SUMMARY_SMART_PAY_TRANSACTIONS_DEV
GROUP BY TRANSACTION_STATUS_KEY
ORDER BY TRANSACTION_STATUS_KEY;