SELECT
    COUNT(*) total_cnt,

    COUNT(*) - COUNT(PRE_APPROVED_INDICATOR) pre_null,

    COUNT(*) - COUNT(VOID_PRE_APPROVED_INDICATOR) void_pre_null,

    COUNT(*) - COUNT(PRODUCT_RISK_OVERRIDE_INDICATOR) product_risk_null,

    COUNT(*) - COUNT(CREDIT_RISK_OVERRIDE_INDICATOR) credit_risk_null,

    COUNT(*) - COUNT(BALANCE_TRANSFER_INDICATOR) bt_null

FROM FDP_UK_CARDS_DB.CREDIT_CARD_APPLICATION_OUTCOME;