SELECT
    TRANSACTION_STATUS_KEY,
    ERROR_MESSAGE_DESCRIPTION,
    SUM(MEASURE_VOLUME) AS VOLUME
FROM BDP_UK_CARDS.FACT_SUMMARY_SMART_PAY_TRANSACTIONS_DEV
WHERE TRANSACTION_STATUS_KEY = 'DROPOUT'
GROUP BY
    TRANSACTION_STATUS_KEY,
    ERROR_MESSAGE_DESCRIPTION
ORDER BY VOLUME DESC;