SELECT DISTINCT a.TRANSACTION_PURPOSE_CODE
FROM FDP_UK_CARDS_DB.PAYMENT_GATEWAY_AUTHORIZATION_TRANSACTION a
WHERE a.TRANSACTION_PURPOSE_CODE NOT IN (
    'DPNGCB',
    'NGCBRF',
    'RL_BLD',
    'RH_BLD',
    'FL_BLD',
    'FH_BLD',
    'IH_BLD',
    'IL_BLD'
);


SELECT DISTINCT s.TRANSACTION_STATUS_CODE
FROM FDP_UK_CARDS_DB.PAYMENT_GATEWAY_TRANSACTION_STATUS s
WHERE s.TRANSACTION_STATUS_CODE NOT IN (
    'PAYMENT_CAPTURED',
    'POSTED',
    'PAYMENT_DECLINED',
    'AUTHORISATION_REQUIRED',
    'CARD_DETAILS_REQUIRED',
    'PAYMENT_AUTHORISED',
    'AUTHENTICATION_REQUIRED',
    'CARD_DETAILS',
    'FAIL',
    'AUTH_FAIL',
    'PAYMENT_FAILED',
    'PAYMENT_CANCELLED'
);