CASE
    WHEN s.TRANSACTION_STATUS_CODE IN (
        'AUTHORISATION_REQUIRED',
        'CARD_DETAILS_REQUIRED',
        'PAYMENT_AUTHORISED',
        'AUTHENTICATION_REQUIRED',
        'CARD_DETAILS'
    )
    THEN COALESCE(
            s.ERROR_DESCRIPTION,
            s.TRANSACTION_STATUS_CODE
         )

    ELSE s.ERROR_DESCRIPTION
END AS ERROR_MESSAGE_DESCRIPTION