WITH expected_status AS (

SELECT COLUMN1 AS STATUS_CODE
FROM VALUES
('AUTHORISATION_REQUIRED'),
('CARD_DETAILS_REQUIRED'),
('DUPLICATE_POSTED_TRAN'),
('FAIL'),
('GATHER_BROWSER_INFO'),
('PAYMENT_AUTHORISED'),
('PAYMENT_CAPTURED'),
('PAYMENT_DECLINED'),
('POSTED'),
('VALIDATION_FAILED'),
('AUTHENTICATION_REQUIRED'),
('AUTH_FAIL'),
('CARD_DETAILS'),
('DIARY_NOTE_MADE'),
('PAYMENT_FAILED'),
('PAYMENT_CANCELLED')

)

SELECT
    DISTINCT s.TRANSACTION_STATUS_CODE
FROM PAYMENT_GATEWAY_TRANSACTION_STATUS s
LEFT JOIN expected_status e
    ON s.TRANSACTION_STATUS_CODE = e.STATUS_CODE
WHERE e.STATUS_CODE IS NULL
ORDER BY 1;