WHERE TRIM(s.TRANSACTION_STATUS_CODE) NOT IN (
    'DUPLICATE_POSTED_TRAN',
    'GATHER_BROWSER_INFO',
    'VALIDATION_FAILED',
    'DIARY_NOTE_MADE'
)
AND TRIM(a.TRANSACTION_PURPOSE_CODE) IN (
    'DPNGCB',
    'NGCBRF',
    'RL_BLD',
    'RH_BLD',
    'FL_BLD',
    'FH_BLD',
    'IH_BLD',
    'IL_BLD'
)
AND NOT (
    TRIM(s.TRANSACTION_STATUS_CODE) IN ('AUTHENTICATE', 'PAYMENT_BEFORE_AUTH')
    AND s.SOURCE_CHANGE_TIMESTAMP > DATEADD(minute, -30, CURRENT_TIMESTAMP())
)