SELECT
    REFERENCE_KEY,
    REFERENCE_DETAIL_NAME,
    REFERENCE_CATEGORY_CODE,
    ACTIVE
FROM BDP_UK_CARDS.DIM_REFERENCE
WHERE REFERENCE_CATEGORY_CODE = 1010
  AND UPPER(REFERENCE_DETAIL_NAME) LIKE '%PAYMENT%FAIL%';