SELECT
    TRIM(s.TRANSACTION_STATUS_CODE) AS TRANSACTION_STATUS_CODE,
    COUNT(*) AS CNT
FROM FDP_UK_CARDS_DB.PAYMENT_GATEWAY_TRANSACTION_STATUS s
LEFT JOIN BDP_UK_CARDS.DIM_REFERENCE ref_status
    ON ref_status.REFERENCE_DETAIL_NAME =
        CASE
            WHEN TRIM(s.TRANSACTION_STATUS_CODE) IN ('PAYMENT_CAPTURED', 'POSTED') THEN 'SUCCESS'
            WHEN TRIM(s.TRANSACTION_STATUS_CODE) = 'PAYMENT_DECLINED' THEN 'DECLINED'
            WHEN TRIM(s.TRANSACTION_STATUS_CODE) IN (
                'AUTHORISATION_REQUIRED',
                'CARD_DETAILS_REQUIRED',
                'PAYMENT_AUTHORISED',
                'AUTHENTICATION_REQUIRED',
                'CARD_DETAILS'
            ) THEN 'DROPOUT'
            WHEN TRIM(s.TRANSACTION_STATUS_CODE) IN ('AUTHENTICATE', 'PAYMENT_BEFORE_AUTH')
                 AND s.SOURCE_CHANGE_TIMESTAMP <= DATEADD(minute, -30, CURRENT_TIMESTAMP()) THEN 'DROPOUT'
            WHEN TRIM(s.TRANSACTION_STATUS_CODE) = 'FAIL' THEN 'REPORTING_ONLY_FAIL'
            WHEN TRIM(s.TRANSACTION_STATUS_CODE) = 'AUTH_FAIL' THEN 'REPORTING_ONLY_AUTH_FAIL'
            WHEN TRIM(s.TRANSACTION_STATUS_CODE) = 'PAYMENT_FAILED' THEN 'REPORTING_ONLY_PAYMENT_FAIL'
            WHEN TRIM(s.TRANSACTION_STATUS_CODE) = 'PAYMENT_CANCELLED' THEN 'REPORTING_ONLY_PAYMENT_CANCELLED'
        END
   AND ref_status.ACTIVE = '1'
   AND ref_status.REFERENCE_CATEGORY_CODE = 1010
WHERE ref_status.REFERENCE_KEY IS NULL
GROUP BY 1
ORDER BY CNT DESC;