SELECT DISTINCT
    APPLICATION_IDENTIFIER,
    APPLICATION_NUMBER
FROM FQ_FINAL2
WHERE APPLICATION_DECISION_DATE = '2026-08-18'
  AND FULL_APPLICATION_STATUS_CODE = 'COMPLETE'
  AND QTIND = 'F'
ORDER BY APPLICATION_IDENTIFIER;