SELECT DISTINCT
    CASE_NUMBER,
    APPLICATION_IDENTIFIER,
    APPLICATION_NUMBER
FROM PROD_BUK_SNSVC0073314_CARDS_BUSINESS_DB.FDP_UK_CARDS_DB.CREDIT_CARD_APPLICATION_CASE
WHERE APPLICATION_DECISION_DATE = '2026-08-18'
  AND FULL_APPLICATION_STATUS_CODE = 'COMPLETE'
ORDER BY CASE_NUMBER;