SELECT
    SOURCE_PRODUCT_CODE,
    COUNT(*) cnt
FROM PROD_BUK_SNSVC0073314_CARDS_BUSINESS_DB
.FDP_UK_CARDS_DB.CREDIT_CARD_APPLICATION_DECISION_OUTCOME
WHERE SOURCE_PRODUCT_CODE IS NOT NULL
GROUP BY SOURCE_PRODUCT_CODE
ORDER BY cnt DESC;