SELECT
    AUDIT_DATE,
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(SOURCE_PRODUCT_CODE IS NOT NULL) AS NON_NULL_ROWS
FROM PROD_BUK_SNSVC0073314_CARDS_BUSINESS_DB
     .FDP_UK_CARDS_DB
     .CREDIT_CARD_APPLICATION_DECISION_OUTCOME
WHERE AUDIT_DATE >= DATEADD(MONTH, -6, CURRENT_DATE())
GROUP BY AUDIT_DATE
HAVING COUNT_IF(SOURCE_PRODUCT_CODE IS NOT NULL) > 0
ORDER BY AUDIT_DATE DESC;