WITH ngcb_ids AS (
    SELECT '226270980' AS ngcb_application_id
)
SELECT
    n.ngcb_application_id,
    app.APPLICATION_NUMBER,
    app.APPLICATION_IDENTIFIER,
    acct.ACCOUNT_NUMBER,
    acct.ACCOUNT_IDENTIFIER
FROM ngcb_ids n
LEFT JOIN FDP_UK_CARDS_DB.CREDIT_CARD_APPLICATION app
    ON app.APPLICATION_NUMBER = n.ngcb_application_id
LEFT JOIN FDP_UK_CARDS_DB.CREDIT_CARD_ACCOUNT acct
    ON acct.APPLICATION_IDENTIFIER = app.APPLICATION_IDENTIFIER
   AND acct.ACTIVE = '1';