SELECT
    APPLICATION_DECISION_DATE,
    CHANNEL_LEVEL_1,
    AGGREGATOR_INDICATOR,
    SUM(BOOKED_ACCOUNTS) AS BOOKED_ACCOUNTS
FROM CARDS.AGGREGATOR_MULTIQUOTE
WHERE APPLICATION_DECISION_DATE = '2026-08-18'
GROUP BY
    APPLICATION_DECISION_DATE,
    CHANNEL_LEVEL_1,
    AGGREGATOR_INDICATOR
ORDER BY
    CHANNEL_LEVEL_1,
    AGGREGATOR_INDICATOR;