SELECT
    APPLICATION_IDENTIFIER,
    SOURCE_PRODUCT_CODE,
    REQUESTED_PRODUCT_CLASS_CODE,
    PRODUCT_CODE,
    AUDIT_DATE,
    AUDIT_TIMESTAMP,
    SDS_COUNTER
FROM PROD_BUK_SNSVC0073314_CARDS_BUSINESS_DB
     .FDP_UK_CARDS_DB
     .CREDIT_CARD_APPLICATION_DECISION_OUTCOME
WHERE APPLICATION_IDENTIFIER IN (
    '第一个Application ID',
    '第二个Application ID'
)
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY APPLICATION_IDENTIFIER
    ORDER BY AUDIT_TIMESTAMP DESC, SDS_COUNTER DESC
) = 1
ORDER BY APPLICATION_IDENTIFIER;