SELECT
    APPLICATION_IDENTIFIER,
    CASE_CREATION_DATE,
    DECISION_DATE,
    REQUESTED_PRODUCT_CLASS_CODE,
    SOURCE_PRODUCT_CODE,
    PRODUCT_CODE,
    ACQ_SEGMENT2 AS OLD_ACQ_SEGMENT2,
    NEW_ACQ_SEGMENT2
FROM FQ_FINAL2
WHERE UPPER(TRIM(ACQ_SEGMENT2)) = 'UNKNOWN'
  AND UPPER(TRIM(NEW_ACQ_SEGMENT2)) = 'UNKNOWN'
ORDER BY APPLICATION_IDENTIFIER;