SELECT
    outc.APPLICATION_IDENTIFIER AS OUTCOME_APPLICATION_IDENTIFIER,
    outc.APPLICATION_NUMBER     AS OUTCOME_APPLICATION_NUMBER,

    elig.APPLICATION_CASE_IDENTIFIER,
    elig.APPLICATION_IDENTIFIER AS ELIG_LONG_APPLICATION_IDENTIFIER,
    elig.APPLICATION_NUMBER     AS ELIG_LONG_APPLICATION_NUMBER,

    acct.APPLICATION_IDENTIFIER AS ACCT_APPLICATION_IDENTIFIER,
    acct.APPLICATION_NUMBER     AS ACCT_APPLICATION_NUMBER,
    acct.ACCOUNT_NUMBER

FROM FDP_UK_CARDS_DB.CREDIT_CARD_APPLICATION_OUTCOME outc

LEFT JOIN FDP_UK_CARDS_DB.CREDIT_CARD_APPLICATION_ELIGIBILITY elig
    ON elig.APPLICATION_CASE_IDENTIFIER = outc.APPLICATION_IDENTIFIER

LEFT JOIN FDP_UK_CARDS_DB.CREDIT_CARD_ACCOUNT acct
    ON acct.APPLICATION_IDENTIFIER = elig.APPLICATION_IDENTIFIER
   AND acct.ACTIVE = '1'

WHERE outc.APPLICATION_NUMBER = '327345002';