SELECT
    RISK_EVALUATION_SCORECARD_NAME,
    GEN_16_BANK_RISK_SCORE,
    NODE_FRAMEWORK_RISK_SEGMENT_CODE,
    NODE_FRAMEWORK_RISK_SEGMENT_KEY,
    COUNT(*) AS RECORD_COUNT
FROM FDP_UK_CARDS_DB_ICBG.CREDIT_CARD_APPLICATION_DECISION_OUTCOME
GROUP BY
    RISK_EVALUATION_SCORECARD_NAME,
    GEN_16_BANK_RISK_SCORE,
    NODE_FRAMEWORK_RISK_SEGMENT_CODE,
    NODE_FRAMEWORK_RISK_SEGMENT_KEY
LIMIT 100;