SELECT
    ACQUISITION_SEGMENT2          AS OLD_ACQ_SEGMENT2,
    NEW_ACQUISITION_SEGMENT2,
    COUNT(*)                      AS RECORD_COUNT,
    COUNT(DISTINCT APPLICATION_IDENTIFIER) AS APPLICATION_COUNT
FROM BASE_SUM_FINAL
GROUP BY
    ACQUISITION_SEGMENT2,
    NEW_ACQUISITION_SEGMENT2
ORDER BY
    OLD_ACQ_SEGMENT2,
    NEW_ACQUISITION_SEGMENT2;