SELECT
    CASE
        WHEN ANNUAL_PERCENTAGE_RATE IS NULL 
         AND APR_PERCENTAGE_APPLIED_AMOUNT IS NULL THEN 'Both NULL'
        WHEN ANNUAL_PERCENTAGE_RATE = APR_PERCENTAGE_APPLIED_AMOUNT THEN 'Matched'
        ELSE 'Different'
    END AS comparison_status,
    COUNT(*) AS cnt
FROM FDP_UK_CARDS_DB.CREDIT_CARD_APPLICATION_OUTCOME
GROUP BY 1
ORDER BY cnt DESC;



SELECT
    APPLICATION_IDENTIFIER,
    ANNUAL_PERCENTAGE_RATE,
    APR_PERCENTAGE_APPLIED_AMOUNT
FROM FDP_UK_CARDS_DB.CREDIT_CARD_APPLICATION_OUTCOME
WHERE COALESCE(ANNUAL_PERCENTAGE_RATE, -999999)
   <> COALESCE(APR_PERCENTAGE_APPLIED_AMOUNT, -999999)
LIMIT 50;