SELECT
    ANNUAL_PERCENTAGE_RATE,
    APR_PERCENTAGE_APPLIED_AMOUNT,
    COUNT(*) AS cnt
FROM FDP_UK_CARDS_DB.CREDIT_CARD_APPLICATION_OUTCOME
GROUP BY
    ANNUAL_PERCENTAGE_RATE,
    APR_PERCENTAGE_APPLIED_AMOUNT
ORDER BY cnt DESC;