SELECT
    APPLICATION_NUMBER,
    APPLICATION_IDENTIFIER,
    APPLICATION_CASE_NUMBER,
    APPLICATION_CASE_IDENTIFIER,
    APPLICATION_REFERENCE_NUMBER,
    APPLICATION_RECEIVE_DATE
FROM FDP_UK_CARDS_DB.CREDIT_CARD_APPLICATION
WHERE APPLICATION_NUMBER IN (
    852813935579207767,
    189192218
);