CASE
    WHEN A.MAIL_NUMBER IS NULL
      OR A.APPLICATION_CHANNEL_CODE IS NULL
    THEN NULL
    ELSE CONCAT(
        LPAD(TRIM(TO_VARCHAR(A.MAIL_NUMBER)), 3, '0'),
        TRIM(A.APPLICATION_CHANNEL_CODE)
    )
END AS ORIGIN_CAMPAIGN_CODE