SELECT DISTINCT
    MAIL_NUMBER,
    APPLICATION_CHANNEL_CODE,
    TO_VARCHAR(MAIL_NUMBER) AS RAW_MAIL_NUMBER,
    LPAD(TO_VARCHAR(MAIL_NUMBER), 3, '0') AS PADDED_MAIL_NUMBER
FROM FDP_UK_CARDS_DB.CREDIT_CARD_APPLICATION_DECISION_OUTCOME
WHERE MAIL_NUMBER IS NOT NULL
   OR APPLICATION_CHANNEL_CODE IS NOT NULL
LIMIT 50;